### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by benjaminathlan** [jaunkst/atom-html2haml#14]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.4
**Thrown From**: [html2haml](https://github.com/jaunkst/atom-html2haml) package, v0.10.0
### Stack Trace

Uncaught SyntaxError: Unexpected token <

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fbenjamin%2Fcode%2Fprojects%2Fsportdub%2Fclean%2Fsportdub-web-rails%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%220.200.0%22%2C%22shellLoadTime%22%3A905%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fbenjamin%2Fcode%2Fprojects%2Fsportdub%2Fclean%2Fsportdub-web-rails%22%5D%7D:1

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/benjamin/.atom/packages/html2haml/lib/html2haml.coffee:53:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)
```
### Commands

```
 17x -1:19 core:move-down (atom-text-editor.editor.is-focused)
  3x -1:17.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:10.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:09.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:08.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:08.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:07.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:07.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:07.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:03.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:02.6.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:02.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:01.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:56.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:56.6.0 html2haml:convert (atom-text-editor.editor)
  9x -0:48.8.0 core:undo (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.6
autocomplete-paths, v1.0.2
github-issues, v0.5.0
html2haml, v0.10.0
language-haml, v0.20.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by onetwopunch** [comment]
+1 same issue on html I grabbed from the javascript console in Chrome

**Comment by penne12** [comment]
+1 Same Issue

**Comment by jibiel** [comment]
One thing I've noticed is that the exception can be circumvented by removing unicode characters from the sample code:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Кириллица</title>
</head>

<body>
  <a target="_blank" href="#"><img src="..." /></a>
</body>

</html>
```

Gives me:

```
Uncaught SyntaxError: Unexpected token <

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/jibiel/.atom/packages/html2haml/lib/html2haml.coffee:45:23)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

While replacing `<title>Кириллица</title>` with `<title>...</title>` gives:

```haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %title ...
  %body
    %a{:href => "#", :target => "_blank"}
      %img{:src => "..."}/
```

**Comment by Kufa-Dev** [comment]
+1 same here

**Comment by JWesorick** [comment]
Having same issue. Happens a lot for me.

**Comment by onetwopunch** [comment]
I guess the fix is don't use HAML ¯\\\_(ツ)\_/¯

**Comment by jaunkst** [comment]
Looking into it.

**Comment by penne12** [comment]
@jaunkst Thanks.

**Comment by jaunkst** [comment]
https://github.com/jaunkst/atom-html2haml/issues/17
