### ISSUE TITLE
Uncaught TypeError: editor.getLastSelection is not a function

### ISSUE THREAD

**Issue by greutter** [jaunkst/atom-html2haml#19]
[Enter steps to reproduce:]

1. Select html
2. Run command

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [html2haml](https://github.com/jaunkst/atom-html2haml) package 0.10.0

### Stack Trace

Uncaught TypeError: editor.getLastSelection is not a function

```
At /Users/greutter/.atom/packages/html2haml/lib/html2haml.coffee:24

TypeError: editor.getLastSelection is not a function
    at Object.convert (/packages/html2haml/lib/html2haml.coffee:24:24)
    at /packages/html2haml/lib/html2haml.coffee:12:85)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:324:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -3:57.6.0 intentions:highlight (input.hidden-input)
  7x -3:48.2.0 core:backspace (input.hidden-input)
     -2:23.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:22.7.0 core:move-right (input.hidden-input)
  2x -2:18.7.0 editor:newline (input.hidden-input)
     -2:17.8.0 core:paste (input.hidden-input)
     -1:24.2.0 core:confirm (input.hidden-input)
     -0:54.7.0 command-palette:toggle (div.panels-item)
     -0:41.3.0 core:confirm (input.hidden-input)
     -0:41.2.0 html2haml:convert (div.panels-item)
     -0:31.4.0 command-palette:toggle (input.hidden-input)
     -0:27.6.0 core:confirm (input.hidden-input)
     -0:27.5.0 html2haml:convert (input.hidden-input)
     -0:05.3.0 command-palette:toggle (input.hidden-input)
     -0:02.4.0 core:confirm (input.hidden-input)
     -0:02.3.0 html2haml:convert (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
busy-signal 1.4.3 
html2haml 0.10.0 
intentions 1.1.5 
language-haml 0.25.2 
linter 2.2.0 
linter-haml 2.0.2 
linter-js-yaml 1.2.8 
linter-ui-default 1.6.10 
```

**Comment by jaunkst** [comment]
Ill look into it soon as I can.
