### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by marshallsherman** [jaunkst/atom-html2haml#3]
Uncaught SyntaxError: Unexpected end of input

**Atom Version**: 0.161.0
**System**: Mac OS X 10.10.1
**Thrown From**: [html2haml](https://github.com/jaunkst/atom-html2haml) package, v0.3.0

### Steps To Reproduce

1. Select a bunch of html in a haml document
2. cmd-shift-p html2haml
3. BOOM

### Stack Trace

```
At file:///Users/marshallsherman/Downloads/Atom.app/Contents/Resources/app/static/index.html?loadSettings=%7B%22bootstrapScript%22%3A%22%2FUsers%2Fmarshallsherman%2FDownloads%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FUsers%2Fmarshallsherman%2FDownloads%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.161.0%22%2C%22shellLoadTime%22%3A199%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at IncomingMessage.<anonymous> (/Users/marshallsherman/.atom/packages/html2haml/lib/html2haml.coffee:40:23)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

/cc @atom/core

**Comment by jaunkst** [comment]
API route changed, updated to newer api route.
