### ISSUE TITLE
Uncaught Error: write after end

### ISSUE THREAD

**Issue by jake69mac** [jaunkst/atom-html2haml#4]
[Enter steps to reproduce below:]

1:  Created new file

This code:
```
<!DOCTYPE html>
<html>
<head>
  <title>Page Title</title>
</head>

<body>
  <h1>This is a Heading</h1>
  <p>This is a paragraph.</p>
</body>

</html>
```

2: Then did cmd + shift + p

3: Selected the html2haml conver

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [html2haml](https://github.com/jaunkst/atom-html2haml) package, v0.6.0

### Stack Trace

Uncaught Error: write after end

```
At events.js:85

Error: write after end
  at ClientRequest.OutgoingMessage.write (_http_outgoing.js:409:15)
  at Object.module.exports.convert (/Users/jakemcallister/.atom/packages/html2haml/lib/html2haml.coffee:46:13)
  at atom-workspace.<anonymous> (/Users/jakemcallister/.atom/packages/html2haml/lib/html2haml.coffee:8:57)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -0:05.7 core:paste (input.hidden-input)
     -0:04.6 command-palette:toggle (input.hidden-input)
     -0:01.6 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-atom-dark-ui)
     -0:00.0 core:confirm (input.hidden-input)
     -0:00.0 html2haml:convert (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
html2haml, v0.6.0
language-emberscript, v0.1.0
language-haml, v0.14.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by andremleblanc** [comment]
I have this issue as well.

**Comment by skipperguy12** [comment]
Same here.

**Comment by ronakrrb** [comment]
Same issue

**Comment by nonameolsson** [comment]
+1

**Comment by mohamed-mahmoud** [comment]
Same issue

**Comment by dudektria** [comment]
Same here.

**Comment by tgaeta** [comment]
+1

**Comment by jaunkst** [comment]
Fixed.
